{
 "title": "TurboGeth Prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "tx_pool_counters",
    "label": "TxPoolCounters",
    "query": "{job=\"geth\"}"
   },
   { "name": "job", "query": "geth" },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   { "name": "instance", "label": "instance", "query": "trie_subtrieloader_flatdb" }
  ]
 },
 "panels": [
  { "title": "Trie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Trie Resolve Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "trie_subtrieloader_flatdb{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "trie_subtrieloader_flatdb: {{quantile}}, {{instance}}"
    },
    {
     "expr": "trie_subtrieloader_witnessdb{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "trie_subtrieloader_witnessdb: {{quantile}}, {{instance}}"
    }
   ]
  },
  {
   "title": "Trie Resolve Amounts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(trie_subtrieloader_flatdb_count{instance=~\"$instance\"}[15m])",
     "legendFormat": "trie_resolve_stateful_count: {{instance}}"
    },
    {
     "expr": "rate(trie_subtrieloader_witnessdb_count{instance=~\"$instance\"}[15m])",
     "legendFormat": "trie_resolve_stateless_count: {{instance}}"
    }
   ]
  },
  {
   "title": "IH Insert/Delete RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_ih_insert{instance=~\"$instance\"}[15m])",
     "legendFormat": "db/ih/insert: {{instance}}"
    },
    {
     "expr": "rate(db_ih_delete{instance=~\"$instance\"}[15m])",
     "legendFormat": "db/ih/delete: {{instance}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_sysload{instance=~\"$instance\"}",
     "legendFormat": "system: {{instance}}"
    },
    {
     "expr": "system_cpu_syswait{instance=~\"$instance\"}",
     "legendFormat": "iowait: {{instance}}"
    },
    {
     "expr": "system_cpu_procload{instance=\"$instance\"}",
     "legendFormat": "geth"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(system_memory_allocs{instance=~\"$instance\"}[1m])",
     "legendFormat": "alloc: {{instance}}"
    },
    {
     "expr": "system_memory_used{instance=~\"$instance\"}",
     "legendFormat": "used: {{instance}}"
    },
    {
     "expr": "system_memory_held{instance=\"$instance\"}",
     "legendFormat": "held"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{instance=~\"$instance\"}[1m])",
     "legendFormat": "read: {{instance}}"
    },
    {
     "expr": "rate(system_disk_writebytes{instance=~\"$instance\"}[1m])",
     "legendFormat": "write: {{instance}}"
    }
   ]
  },
  {
   "title": "GC Stop the World",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(system_memory_pauses{instance=~\"$instance\"}[1m])",
     "legendFormat": "system/memory/pauses: {{instance}}"
    }
   ]
  },
  {
   "title": "GO Goroutines and Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "go/goroutines: {{instance}}"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "go/threads: {{instance}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=~\"$instance\"}[1m])",
     "legendFormat": "ingress: {{instance}}"
    },
    {
     "expr": "rate(p2p_egress{instance=~\"$instance\"}[1m])",
     "legendFormat": "egress: {{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "peers: {{instance}}"
    },
    {
     "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
     "legendFormat": "dials: {{instance}}"
    },
    {
     "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
     "legendFormat": "serves: {{instance}}"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Latest header",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "chain_head_header" }
   ]
  },
  {
   "title": "Chain head",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chain_head_header{instance=~\"$instance\"}",
     "legendFormat": "header: {{instance}}"
    },
    {
     "expr": "chain_head_receipt{instance=~\"$instance\"}",
     "legendFormat": "receipt: {{instance}}"
    },
    {
     "expr": "chain_head_block{instance=~\"$instance\"}",
     "legendFormat": "block: {{instance}}"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "txpool_pending" }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "executable: {{instance}}"
    },
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "gapped: {{instance}}"
    },
    {
     "expr": "txpool_local{instance=~\"$instance\"}",
     "legendFormat": "local: {{instance}}"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "chain_head_receipt" }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "txpool_queued" }
   ]
  },
  {
   "title": "Latest block",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "chain_head_block" }
   ]
  },
  {
   "title": "Local transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 33 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "txpool_local" }
   ]
  },
  {
   "title": "Block processing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "chain_execution{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "execution: {{quantile}},  {{instance}}"
    },
    {
     "expr": "chain_validation{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "validation: {{quantile}},  {{instance}}"
    },
    {
     "expr": "chain_write{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "commit: {{quantile}},  {{instance}}"
    },
    {
     "expr": "chain_account_reads{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "account read: {{quantile}},  {{instance}}"
    },
    {
     "expr": "chain_account_updates{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "account update: {{quantile}},  {{instance}}"
    },
    {
     "expr": "chain_account_hashes{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "account hashe: {{quantile}},  {{instance}}"
    },
    {
     "expr": "chain_account_commits{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "account commit: {{quantile}},  {{instance}}"
    },
    {
     "expr": "chain_storage_reads{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "storage read: {{quantile}},  {{instance}}"
    },
    {
     "expr": "chain_storage_updates{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "storage update: {{quantile}},  {{instance}}"
    },
    {
     "expr": "chain_storage_hashes{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "storage hashe: {{quantile}},  {{instance}}"
    },
    {
     "expr": "chain_storage_commits{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "storage commit: {{quantile}},  {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(txpool_valid{instance=~\"$instance\"}[1m])",
     "legendFormat": "valid: {{instance}}"
    },
    {
     "expr": "rate(txpool_invalid{instance=~\"$instance\"}[1m])",
     "legendFormat": "invalid: {{instance}}"
    },
    {
     "expr": "rate(txpool_underpriced{instance=\"$instance\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write[1m])",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read[1m])",
     "legendFormat": "ancient read"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write[1m])",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "eth_db_chaindata_disk_read", "legendFormat": "leveldb read" },
    { "expr": "eth_db_chaindata_disk_write", "legendFormat": "leveldb write" },
    { "expr": "eth_db_chaindata_ancient_read", "legendFormat": "ancient read" },
    { "expr": "eth_db_chaindata_ancient_write", "legendFormat": "ancient write" }
   ]
  },
  {
   "title": "Storage size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "eth_db_chaindata_disk_size", "legendFormat": "leveldb" },
    { "expr": "eth_db_chaindata_ancient_size", "legendFormat": "ancient" }
   ]
  },
  { "title": "Trie Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Clean cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(trie_memcache_clean_read{instance=~\"$instance\"}[1m])",
     "legendFormat": "hit: {{instance}}"
    },
    {
     "expr": "rate(trie_memcache_clean_write{instance=~\"$instance\"}[1m])",
     "legendFormat": "miss: {{instance}}"
    }
   ]
  },
  {
   "title": "Dirty cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_size{instance=~\"$instance\"}[1m])",
     "legendFormat": "gc: {{instance}}"
    },
    {
     "expr": "rate(trie_memcache_flush_size{instance=~\"$instance\"}[1m])",
     "legendFormat": "overflow: {{instance}}"
    },
    {
     "expr": "rate(trie_memcache_commit_size[1m])",
     "legendFormat": "commit"
    }
   ]
  }
 ]
}